---
# lint this file: docker-compose config
version: '3'

services:
  app:
    container_name: ${DOCKER_PROJECT}-service
    image: "${DOCKER_BUILD_IMAGE_NAMETAG_LATEST}"
    ports:
    - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{"spring": {"data": {"mongodb": {"uri": "mongodb://datastore:27017/test"}}}}'

  datastore:
    container_name: ${DOCKER_PROJECT}-mongodb
    image: ${DOCKER_GROUP}/mongo-sample-data:3.4-r0
    ports:
     - 27117:27017
